
version: 2

models:
  - name: positions
    description: "consolidated position view"
    columns:
      - name: id
        description: "The primary key for position"
        tests:
          - unique
          - not_null

  - name: position_5
    description: "position 5 model"
    columns:
      - name: id
        description: "The primary key for position 5 model"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ['1_5', '1_6', '1_7', '1_8']