demo_project:
  outputs:
    dev_user:
      catalog: null
      host: adb-8520072511810930.10.azuredatabricks.net   #dev user      
      http_path: /sql/1.0/warehouses/c5a6d4788cf441bc    #dev user - sql warehouse starter endpoint       
      token: dapi17d6ac08ec00b87578f31045149084d8    #dev user      
      schema: default 
      threads: 5
      retry_all: true
      connect_retries: 2
      type: databricks
    dev_pipeline:
      catalog: null
      host: adb-3881115180254026.6.azuredatabricks.net   #dev pipeline 
      http_path: sql/protocolv1/o/3881115180254026/0928-012617-credo999  #dev pipeline - devCluster
      # http_path: sql/protocolv1/o/3881115180254026/0518-030501-wm1m5tx3    #dev pipeline - Unity Catalog trial       
      token: dapi115b9cb3e0e021d59a0355bb5241e64f    #dev pipeline    
      schema: default 
      threads: 5
      retry_all: true
      connect_retries: 2
      type: databricks   
    uat_pipeline:
      catalog: null
      host: adb-5843594888392012.12.azuredatabricks.net   #uat pipeline 
      http_path: sql/protocolv1/o/5843594888392012/1005-232131-flash802  #uat pipeline - uatCluster   
      token: dapi7c75840d6ea274ab576f6988122f4ba8    #uat pipeline    
      schema: default 
      threads: 5
      retry_all: true
      connect_retries: 2
      type: databricks
    uat_pipeline_sql:
      catalog: null
      host: adb-5843594888392012.12.azuredatabricks.net   #uat pipeline 
      http_path: /sql/1.0/warehouses/2068488f4e49f3aa  #DBT PoC Endpoint   
      token: dapi7c75840d6ea274ab576f6988122f4ba8    #uat pipeline    
      schema: default 
      threads: 5
      retry_all: true
      connect_retries: 2
      type: databricks        
  target: uat_pipeline