demo_project:
  outputs:
    dev:
      catalog: null
      host: adb-3881115180254026.6.azuredatabricks.net
      http_path: sql/protocolv1/o/3881115180254026/0928-012617-credo999
      token: dapic96d460b34329e65c8c9c4987533cc61
      schema: default
      threads: 3
      type: databricks
  target: dev