demo_project:
  outputs:
    dev:
      catalog: null
      host: adb-4492709390385172.12.azuredatabricks.net
      http_path: sql/protocolv1/o/4492709390385172/0307-035111-ovhp103l
      schema: default
      threads: 3
      type: databricks
  target: dev
