demo_project:
  outputs:
    dev_user:
      catalog: null
      host: adb-8520072511810930.10.azuredatabricks.net   #dev user      
      http_path: /sql/1.0/warehouses/c5a6d4788cf441bc    #dev user - sql warehouse starter endpoint       
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"    #dev user      
      schema: default 
      threads: 5
      retry_all: true
      connect_retries: 2
      type: databricks
    dev:
      catalog: null
      # catalog: dev      
      host: adb-3881115180254026.6.azuredatabricks.net   #dev pipeline 
      http_path: sql/protocolv1/o/3881115180254026/0928-012617-credo999  #dev pipeline - devCluster
      # http_path: sql/protocolv1/o/3881115180254026/0518-030501-wm1m5tx3    #dev pipeline - Unity Catalog trial       
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"         
      schema: default 
      threads: 5
      retry_all: true
      connect_retries: 1
      type: databricks   
    uat_pipeline:
      catalog: null
      host: adb-5843594888392012.12.azuredatabricks.net   #uat pipeline 
      http_path: sql/protocolv1/o/5843594888392012/1005-232131-flash802  #uat pipeline - uatCluster   
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"    #uat pipeline    
      schema: default 
      threads: 5
      retry_all: true
      connect_retries: 2
      type: databricks
    uat_pipeline_sql:
      catalog: null
      host: adb-5843594888392012.12.azuredatabricks.net   #uat pipeline 
      http_path: /sql/1.0/warehouses/2068488f4e49f3aa  #DBT PoC Endpoint   
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"    #uat pipeline    
      schema: default 
      threads: 5
      retry_all: true
      connect_retries: 2
      type: databricks        
  target: dev
